version: "3.7"

services:

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        USERNAME: ${USERNAME}
        GROUPNAME: ${GROUPNAME}
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./backend/:/api
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - backend
    volumes:
      - ./backend/:/api

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    #      args:
    #        - TZ=${TZ}
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - ${FRONT_PORT}:3333